### ISSUE TITLE
Mistake on a branding picture

### ISSUE THREAD

**Issue by Marmous** [ONEARMY/fixing-fashion-academy#17]
There is a mistake on the colours sample picture [here](https://community.fixing.fashion/academy/other/branding#icon--colors).
#F82F03 refers to the red. The black colour seems to be #000000.

**Comment by darigovresearch** [comment]
Thanks @Marmous for raising the issue I concur that it appears both the red and the black have been labelled with the same colour. Would you care to make a pull request with the corrected image and adjusted text?

**Comment by Marmous** [comment]
I'll try to do so, since I'm new to github it may take some time.

**Comment by darigovresearch** [comment]
@Marmous thanks for taking a look & major respect for having a go even if you're new to GitHub. If given admin rights to become a maintainer of the repo we would also add the tag "Good first issue" and "Help wanted" to encourage other people as well to make the modification, maybe @chrismclarke can advise on if that is possible. But Marmous you might as well have a go as it should be easy to accept.

If you need general guidance on how to make a pull request you can take a look at the video we made to help anyone new to GitHub contribute to open source. 

https://www.youtube.com/watch?v=UWA4wyacY2A

Do you know how to edit photos? 

If you're new to that would recommend using the [GNU Image Manipulation Program](https://www.gimp.org/) as it is free, open source and many tutorials can be found online.

**Comment by Marmous** [comment]
Thank you for your help, I'm going to watch the video.
One point for GIMP, I've already used it.
Do you know which font have been used in the picture ?

**Comment by Marmous** [comment]
Oh, another point, the logos and icons links are broken [here](https://github.com/ONEARMY/fixing-fashion-academy/blob/master/docs/other/branding.md).

**Comment by darigovresearch** [comment]
You're very welcome. On the font I don't believe this has been specified, you can try the ones listed here and see which ones look the most similar but these may not work as it s for the website & not assets like in this example https://github.com/ONEARMY/fixing-fashion-academy/blob/4e73fefc11745f682a153830f16fd76219fbe7ba/website/siteConfig.js#L61-L78

On the broken links this is normal as the source format that links images correctly is designed to render images in the final output which is the fixing.fashion academy & not these GitHub pages

**Comment by Marmous** [comment]
Ok, thank you, I'll try with those

**Comment by Marmous** [comment]
I am about to launch a pull request, are they some requirements to do so?

**Comment by darigovresearch** [comment]
This is an early stage project so believe at this point in time there are no requirements for the pull request apart from the fact that (which is assumed) your pull request will be under the same open source license as the source repository

**Comment by Marmous** [comment]
All right.
Do the original repo license automatically consider that the pull request is under the same license or is it an implicit rule here?

**Comment by darigovresearch** [comment]
Great question, not a lawyer so can't say but it may depend on what the source license of the repository is and if it assumes all derivative works must use the same license.

Out of curiosity what was the correct font in the end?

**Comment by Marmous** [comment]
Finally, I didn't use a text box with a specific font, just took a `0` in the picture and copied/pasted it regularly.

**Comment by darigovresearch** [comment]
Very clever outside the box thinking, nice work!

**Comment by chrismclarke** [comment]
>  If given admin rights to become a maintainer of the repo we would also add the tag "Good first issue" and "Help wanted" to encourage other people as well to make the modification, maybe @chrismclarke can advise on if that is possible. 

@darigovresearch - I sent @davehakkens a message to try organise invites/permissions etc. Agree these things are always good to have (and usually not much work at all, just good to have someone tagging things that's a bit more responsive than me!).

**Comment by darigovresearch** [comment]
@chrismclarke thanks for sending @davehakkens a message, would agree that having more trusted people who have elevated privileges makes community driven contributions much easier

**Comment by chrismclarke** [comment]
Yeah, and github is pretty nice/flexible with permissions. As a minimum being able to organise labels for help-wanted and good first issue is a nice way to encourage people to get involved - I'll also add it to the agenda for the next monthly dev call just to check where we are with those things.

**Comment by darigovresearch** [comment]
Sounds good
