### ISSUE TITLE
[BUG] Missing License

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/fixing-fashion-academy#5]
On the fixing fashion website, academy or their corresponding GitHub repositories there hasn't been any mention of a license of either the content or the code.

Would assume that the content would be CC-BY-SA or the like as with precious plastic.

Having an explicit license would encourage contributions to the original work along with people building on top of it.

Can anyone from the team advise or has this been left out on purpose?

**Comment by davehakkens** [comment]
Not on purpose, just forgot.
Feel free to make a pull request and i'll add

**Comment by darigovresearch** [comment]
No worries, Pull request #6 should resolve the issue but feel free to make any amendments or corrections as required.

We really like the open source page for the precious plastic website and so may be good to make a page for it as well on the fixing fashion site as well if possible.

Page in question - https://preciousplastic.com/about/open-source

**Comment by davehakkens** [comment]
yeh. Perhaps for v2 
But there is less "open source" feeling to that project.
No drawings, no bom, blueprints etc..
Mainly videos and text.

**Comment by darigovresearch** [comment]
Yeah You may find people will want to contribute patterns for making specific items using old clothes. Some good easy projects for blueprints/patterns would be pleated face coverings which can be reused, bow ties etc

Another open source fashion project - https://freesewing.org/

**Comment by darigovresearch** [comment]
Pull request #6 resolved this issue so will close this issue
